version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      db:
        condition: service_started
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - fastapi-net

  db:
    image: postgres:15
    container_name: fastapi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    networks:
      - fastapi-net

networks:
  fastapi-net:
